- name: Install Apache
  hosts: ubuntu_servers
  become: true

  tasks:
  - name: Update apt package cache
    apt:
      update_cache: yes

  - name: Install Apache
    apt:
      name: apache2
      state: present
    notify:
    - Start Apache

  - name: Configure Server Details
    shell: |
      echo "<h1>Server Detail</h1><p><strong>Hostname:</strong> $(hostname)</p>
      <p><strong>IP Address:</strong> $(hostname -i | cut -d' ' -f1)</p>" > /var/www/html/index.html
    become: true
    notify:
    - Restart Apache

  handlers:
  - name: Start Apache
    service:
      name: apache2
      state: started
      enabled: yes

  - name: Restart Apache
    service:
      name: apache2
      state: restarted
